safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "LC-LeetCode"
description: "Discuss issues on coding interview"
baseurl: ""
url: "https://undertree93.github.com/lc-leetcode" # replace by your site's url
github_username:  undertree93 # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Undertree93"
address: "Markham, Ontario, Canada"
email: "undertree93@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md